# Generated by Django 3.0.8 on 2020-08-03 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('priceapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PricingPlanOptions',
            new_name='PricingPlanOption',
        ),
    ]
