# Generated by Django 3.0.8 on 2020-08-04 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('priceapp', '0002_auto_20200803_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricingplan',
            name='pp_id',
        ),
        migrations.RemoveField(
            model_name='pricingplanoption',
            name='ppo_id',
        ),
        migrations.AlterField(
            model_name='pricingplanoption',
            name='createdate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pricingplanoption',
            name='updatedate',
            field=models.DateField(auto_now=True),
        ),
    ]
